const SET_MYFAV = "SET_MYFAV",
  DELETE_MYFAV = "DELETE_MYFAV",
  SET_VALIDACION = "SET_VALIDACION",
  SET_EXISTE = "SET_EXISTE",
  SET_CARGANDO = "SET_CARGANDO",
  SET_SEARCHBAR = "SET_SEARCHBAR",
  SET_BACK = "SET_BACK",
  SET_FILTER = "SET_FILTER",
  SET_ALLCARD = "SET_ALLCARD",
  SET_MYCARD = "SET_MYCARD",
  SET_ALLFAVORITES = "SET_ALLFAVORITES",
  DELETE_ALLFAVORITES = "DELETE_ALLFAVORITES",
  SET_ACTIVEFIL = "SET_ACTIVEFIL";



export {
  SET_MYFAV,
  DELETE_MYFAV,
  SET_VALIDACION,
  SET_EXISTE,
  SET_CARGANDO,
  SET_SEARCHBAR,
  SET_BACK,
  SET_FILTER,
  SET_ALLCARD,
  SET_MYCARD,
  SET_ALLFAVORITES,
  DELETE_ALLFAVORITES,
  SET_ACTIVEFIL,
};
