const SET_MYFAV = "SET_MYFAV",
  DELETE_MYFAV = "DELETE_MYFAV",
  SET_VALIDACION = "SET_VALIDACION",
  SET_EXISTE = "SET_EXISTE",
  SET_CARGANDO = "SET_CARGANDO",
  SET_SEARCHBAR = "SET_SEARCHBAR",
  SET_BACK = "SET_BACK";
export { SET_MYFAV, DELETE_MYFAV, SET_VALIDACION, SET_EXISTE, SET_CARGANDO, SET_SEARCHBAR, SET_BACK };
